// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct ChopTerrainArgs {
    pub pos_x: i32,
    pub pos_y: i32,
    pub pos_z: i32,
    pub size: i32,
}

impl Reducer for ChopTerrainArgs {
    const REDUCER_NAME: &'static str = "chop_terrain";
}

#[allow(unused)]
pub fn chop_terrain(pos_x: i32, pos_y: i32, pos_z: i32, size: i32) {
    ChopTerrainArgs {
        pos_x,
        pos_y,
        pos_z,
        size,
    }
    .invoke();
}

#[allow(unused)]
pub fn on_chop_terrain(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &i32, &i32, &i32, &i32)
        + Send
        + 'static,
) -> ReducerCallbackId<ChopTerrainArgs> {
    ChopTerrainArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let ChopTerrainArgs {
            pos_x,
            pos_y,
            pos_z,
            size,
        } = __args;
        __callback(__identity, __addr, __status, pos_x, pos_y, pos_z, size);
    })
}

#[allow(unused)]
pub fn once_on_chop_terrain(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &i32, &i32, &i32, &i32)
        + Send
        + 'static,
) -> ReducerCallbackId<ChopTerrainArgs> {
    ChopTerrainArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let ChopTerrainArgs {
            pos_x,
            pos_y,
            pos_z,
            size,
        } = __args;
        __callback(__identity, __addr, __status, pos_x, pos_y, pos_z, size);
    })
}

#[allow(unused)]
pub fn remove_on_chop_terrain(id: ReducerCallbackId<ChopTerrainArgs>) {
    ChopTerrainArgs::remove_on_reducer(id);
}
