// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::stdb_position_look_packet::StdbPositionLookPacket;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct HandlePositionLookArgs {
    pub entity_id: u32,
    pub packet: StdbPositionLookPacket,
}

impl Reducer for HandlePositionLookArgs {
    const REDUCER_NAME: &'static str = "handle_position_look";
}

#[allow(unused)]
pub fn handle_position_look(entity_id: u32, packet: StdbPositionLookPacket) {
    HandlePositionLookArgs { entity_id, packet }.invoke();
}

#[allow(unused)]
pub fn on_handle_position_look(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u32, &StdbPositionLookPacket)
        + Send
        + 'static,
) -> ReducerCallbackId<HandlePositionLookArgs> {
    HandlePositionLookArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let HandlePositionLookArgs { entity_id, packet } = __args;
        __callback(__identity, __addr, __status, entity_id, packet);
    })
}

#[allow(unused)]
pub fn once_on_handle_position_look(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u32, &StdbPositionLookPacket)
        + Send
        + 'static,
) -> ReducerCallbackId<HandlePositionLookArgs> {
    HandlePositionLookArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let HandlePositionLookArgs { entity_id, packet } = __args;
        __callback(__identity, __addr, __status, entity_id, packet);
    })
}

#[allow(unused)]
pub fn remove_on_handle_position_look(id: ReducerCallbackId<HandlePositionLookArgs>) {
    HandlePositionLookArgs::remove_on_reducer(id);
}
