// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::in_login_packet::InLoginPacket;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct HandleLoginArgs {
    pub connection_id: u32,
    pub packet: InLoginPacket,
}

impl Reducer for HandleLoginArgs {
    const REDUCER_NAME: &'static str = "handle_login";
}

#[allow(unused)]
pub fn handle_login(connection_id: u32, packet: InLoginPacket) {
    HandleLoginArgs {
        connection_id,
        packet,
    }
    .invoke();
}

#[allow(unused)]
pub fn on_handle_login(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u32, &InLoginPacket)
        + Send
        + 'static,
) -> ReducerCallbackId<HandleLoginArgs> {
    HandleLoginArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let HandleLoginArgs {
            connection_id,
            packet,
        } = __args;
        __callback(__identity, __addr, __status, connection_id, packet);
    })
}

#[allow(unused)]
pub fn once_on_handle_login(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u32, &InLoginPacket) + Send + 'static,
) -> ReducerCallbackId<HandleLoginArgs> {
    HandleLoginArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let HandleLoginArgs {
            connection_id,
            packet,
        } = __args;
        __callback(__identity, __addr, __status, connection_id, packet);
    })
}

#[allow(unused)]
pub fn remove_on_handle_login(id: ReducerCallbackId<HandleLoginArgs>) {
    HandleLoginArgs::remove_on_reducer(id);
}
