// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::stdb_position_packet::StdbPositionPacket;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct HandlePositionArgs {
    pub entity_id: u32,
    pub packet: StdbPositionPacket,
}

impl Reducer for HandlePositionArgs {
    const REDUCER_NAME: &'static str = "handle_position";
}

#[allow(unused)]
pub fn handle_position(entity_id: u32, packet: StdbPositionPacket) {
    HandlePositionArgs { entity_id, packet }.invoke();
}

#[allow(unused)]
pub fn on_handle_position(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u32, &StdbPositionPacket)
        + Send
        + 'static,
) -> ReducerCallbackId<HandlePositionArgs> {
    HandlePositionArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let HandlePositionArgs { entity_id, packet } = __args;
        __callback(__identity, __addr, __status, entity_id, packet);
    })
}

#[allow(unused)]
pub fn once_on_handle_position(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u32, &StdbPositionPacket)
        + Send
        + 'static,
) -> ReducerCallbackId<HandlePositionArgs> {
    HandlePositionArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let HandlePositionArgs { entity_id, packet } = __args;
        __callback(__identity, __addr, __status, entity_id, packet);
    })
}

#[allow(unused)]
pub fn remove_on_handle_position(id: ReducerCallbackId<HandlePositionArgs>) {
    HandlePositionArgs::remove_on_reducer(id);
}
