// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct SetTimeArgs {
    pub time: u64,
}

impl Reducer for SetTimeArgs {
    const REDUCER_NAME: &'static str = "set_time";
}

#[allow(unused)]
pub fn set_time(time: u64) {
    SetTimeArgs { time }.invoke();
}

#[allow(unused)]
pub fn on_set_time(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u64) + Send + 'static,
) -> ReducerCallbackId<SetTimeArgs> {
    SetTimeArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let SetTimeArgs { time } = __args;
        __callback(__identity, __addr, __status, time);
    })
}

#[allow(unused)]
pub fn once_on_set_time(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u64) + Send + 'static,
) -> ReducerCallbackId<SetTimeArgs> {
    SetTimeArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let SetTimeArgs { time } = __args;
        __callback(__identity, __addr, __status, time);
    })
}

#[allow(unused)]
pub fn remove_on_set_time(id: ReducerCallbackId<SetTimeArgs>) {
    SetTimeArgs::remove_on_reducer(id);
}
