// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::world::World;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbWorld {
    pub id: i32,
    pub world: World,
}

impl TableType for StdbWorld {
    const TABLE_NAME: &'static str = "StdbWorld";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for StdbWorld {
    type PrimaryKey = i32;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.id
    }
}

impl StdbWorld {
    #[allow(unused)]
    pub fn filter_by_id(id: i32) -> TableIter<Self> {
        Self::filter(|row| row.id == id)
    }
    #[allow(unused)]
    pub fn find_by_id(id: i32) -> Option<Self> {
        Self::find(|row| row.id == id)
    }
}
