// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::chunk_event::ChunkEvent;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbChunkEvent {
    pub x: i32,
    pub z: i32,
    pub inner: ChunkEvent,
}

impl TableType for StdbChunkEvent {
    const TABLE_NAME: &'static str = "StdbChunkEvent";
    type ReducerEvent = super::ReducerEvent;
}

impl StdbChunkEvent {
    #[allow(unused)]
    pub fn filter_by_x(x: i32) -> TableIter<Self> {
        Self::filter(|row| row.x == x)
    }
    #[allow(unused)]
    pub fn filter_by_z(z: i32) -> TableIter<Self> {
        Self::filter(|row| row.z == z)
    }
}
