// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbTrackedPlayer {
    pub track_id: u32,
    pub from_id: u32,
    pub to_id: u32,
}

impl TableType for StdbTrackedPlayer {
    const TABLE_NAME: &'static str = "StdbTrackedPlayer";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for StdbTrackedPlayer {
    type PrimaryKey = u32;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.track_id
    }
}

impl StdbTrackedPlayer {
    #[allow(unused)]
    pub fn filter_by_track_id(track_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.track_id == track_id)
    }
    #[allow(unused)]
    pub fn find_by_track_id(track_id: u32) -> Option<Self> {
        Self::find(|row| row.track_id == track_id)
    }
    #[allow(unused)]
    pub fn filter_by_from_id(from_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.from_id == from_id)
    }
    #[allow(unused)]
    pub fn filter_by_to_id(to_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.to_id == to_id)
    }
}
