// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::stdb_d_vec_3::StdbDVec3;
use super::stdb_vec_2::StdbVec2;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbOfflinePlayer {
    pub entity_id: u32,
    pub username: String,
    pub world: String,
    pub pos: StdbDVec3,
    pub look: StdbVec2,
}

impl TableType for StdbOfflinePlayer {
    const TABLE_NAME: &'static str = "StdbOfflinePlayer";
    type ReducerEvent = super::ReducerEvent;
}

impl StdbOfflinePlayer {
    #[allow(unused)]
    pub fn filter_by_entity_id(entity_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.entity_id == entity_id)
    }
    #[allow(unused)]
    pub fn filter_by_username(username: String) -> TableIter<Self> {
        Self::filter(|row| row.username == username)
    }
    #[allow(unused)]
    pub fn filter_by_world(world: String) -> TableIter<Self> {
        Self::filter(|row| row.world == world)
    }
}
