// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

use super::weather::Weather;
#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbWeather {
    pub id: u32,
    pub weather_next_time: u64,
    pub weather: Weather,
}

impl TableType for StdbWeather {
    const TABLE_NAME: &'static str = "StdbWeather";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for StdbWeather {
    type PrimaryKey = u32;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.id
    }
}

impl StdbWeather {
    #[allow(unused)]
    pub fn filter_by_id(id: u32) -> Option<Self> {
        Self::find(|row| row.id == id)
    }
    #[allow(unused)]
    pub fn filter_by_weather_next_time(weather_next_time: u64) -> TableIter<Self> {
        Self::filter(|row| row.weather_next_time == weather_next_time)
    }
    #[allow(unused)]
    pub fn filter_by_weather(weather: Weather) -> TableIter<Self> {
        Self::filter(|row| row.weather == weather)
    }
}
