// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

use super::dimension::Dimension;
use super::java_random::JavaRandom;
use super::light_update::LightUpdate;
#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct World {
    pub dimension: Dimension,
    pub time: u64,
    pub rand: JavaRandom,
    pub entities_count: u32,
    pub light_updates: Vec<LightUpdate>,
    pub random_ticks_seed: i32,
    pub sky_light_subtracted: u8,
}
