// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::biome::Biome;
use super::chunk_nibble_array_3::ChunkNibbleArray3;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct Chunk {
    pub block: Vec<u8>,
    pub metadata: ChunkNibbleArray3,
    pub block_light: ChunkNibbleArray3,
    pub sky_light: ChunkNibbleArray3,
    pub height: Vec<u8>,
    pub biome: Vec<Biome>,
}
