// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::stdb_look_packet::StdbLookPacket;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct HandleLookArgs {
    pub entity_id: u32,
    pub packet: StdbLookPacket,
}

impl Reducer for HandleLookArgs {
    const REDUCER_NAME: &'static str = "handle_look";
}

#[allow(unused)]
pub fn handle_look(entity_id: u32, packet: StdbLookPacket) {
    HandleLookArgs { entity_id, packet }.invoke();
}

#[allow(unused)]
pub fn on_handle_look(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u32, &StdbLookPacket)
        + Send
        + 'static,
) -> ReducerCallbackId<HandleLookArgs> {
    HandleLookArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let HandleLookArgs { entity_id, packet } = __args;
        __callback(__identity, __addr, __status, entity_id, packet);
    })
}

#[allow(unused)]
pub fn once_on_handle_look(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u32, &StdbLookPacket) + Send + 'static,
) -> ReducerCallbackId<HandleLookArgs> {
    HandleLookArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let HandleLookArgs { entity_id, packet } = __args;
        __callback(__identity, __addr, __status, entity_id, packet);
    })
}

#[allow(unused)]
pub fn remove_on_handle_look(id: ReducerCallbackId<HandleLookArgs>) {
    HandleLookArgs::remove_on_reducer(id);
}
