// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbHandSlot {
    pub player_id: u32,
    pub slot_id: u32,
}

impl TableType for StdbHandSlot {
    const TABLE_NAME: &'static str = "StdbHandSlot";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for StdbHandSlot {
    type PrimaryKey = u32;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.player_id
    }
}

impl StdbHandSlot {
    #[allow(unused)]
    pub fn filter_by_player_id(player_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.player_id == player_id)
    }
    #[allow(unused)]
    pub fn find_by_player_id(player_id: u32) -> Option<Self> {
        Self::find(|row| row.player_id == player_id)
    }
    #[allow(unused)]
    pub fn filter_by_slot_id(slot_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.slot_id == slot_id)
    }
}
