// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbHandleAcceptArgs {
    pub connection_id: u64,
}

impl Reducer for StdbHandleAcceptArgs {
    const REDUCER_NAME: &'static str = "stdb_handle_accept";
}

#[allow(unused)]
pub fn stdb_handle_accept(connection_id: u64) {
    StdbHandleAcceptArgs { connection_id }.invoke();
}

#[allow(unused)]
pub fn on_stdb_handle_accept(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u64) + Send + 'static,
) -> ReducerCallbackId<StdbHandleAcceptArgs> {
    StdbHandleAcceptArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let StdbHandleAcceptArgs { connection_id } = __args;
        __callback(__identity, __addr, __status, connection_id);
    })
}

#[allow(unused)]
pub fn once_on_stdb_handle_accept(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u64) + Send + 'static,
) -> ReducerCallbackId<StdbHandleAcceptArgs> {
    StdbHandleAcceptArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let StdbHandleAcceptArgs { connection_id } = __args;
        __callback(__identity, __addr, __status, connection_id);
    })
}

#[allow(unused)]
pub fn remove_on_stdb_handle_accept(id: ReducerCallbackId<StdbHandleAcceptArgs>) {
    StdbHandleAcceptArgs::remove_on_reducer(id);
}
