// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbEntityView {
    pub view_id: u32,
    pub observer_id: u32,
    pub target_id: u32,
}

impl TableType for StdbEntityView {
    const TABLE_NAME: &'static str = "StdbEntityView";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for StdbEntityView {
    type PrimaryKey = u32;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.view_id
    }
}

impl StdbEntityView {
    #[allow(unused)]
    pub fn filter_by_view_id(view_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.view_id == view_id)
    }
    #[allow(unused)]
    pub fn find_by_view_id(view_id: u32) -> Option<Self> {
        Self::find(|row| row.view_id == view_id)
    }
    #[allow(unused)]
    pub fn filter_by_observer_id(observer_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.observer_id == observer_id)
    }
    #[allow(unused)]
    pub fn filter_by_target_id(target_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.target_id == target_id)
    }
}
