// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::stdb_break_block_packet::StdbBreakBlockPacket;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbHandleBreakBlockArgs {
    pub entity_id: u32,
    pub packet: StdbBreakBlockPacket,
}

impl Reducer for StdbHandleBreakBlockArgs {
    const REDUCER_NAME: &'static str = "stdb_handle_break_block";
}

#[allow(unused)]
pub fn stdb_handle_break_block(entity_id: u32, packet: StdbBreakBlockPacket) {
    StdbHandleBreakBlockArgs { entity_id, packet }.invoke();
}

#[allow(unused)]
pub fn on_stdb_handle_break_block(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u32, &StdbBreakBlockPacket)
        + Send
        + 'static,
) -> ReducerCallbackId<StdbHandleBreakBlockArgs> {
    StdbHandleBreakBlockArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let StdbHandleBreakBlockArgs { entity_id, packet } = __args;
        __callback(__identity, __addr, __status, entity_id, packet);
    })
}

#[allow(unused)]
pub fn once_on_stdb_handle_break_block(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u32, &StdbBreakBlockPacket)
        + Send
        + 'static,
) -> ReducerCallbackId<StdbHandleBreakBlockArgs> {
    StdbHandleBreakBlockArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let StdbHandleBreakBlockArgs { entity_id, packet } = __args;
        __callback(__identity, __addr, __status, entity_id, packet);
    })
}

#[allow(unused)]
pub fn remove_on_stdb_handle_break_block(id: ReducerCallbackId<StdbHandleBreakBlockArgs>) {
    StdbHandleBreakBlockArgs::remove_on_reducer(id);
}
