// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::stdb_place_block_packet::StdbPlaceBlockPacket;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbHandlePlaceBlockArgs {
    pub player_id: u32,
    pub packet: StdbPlaceBlockPacket,
}

impl Reducer for StdbHandlePlaceBlockArgs {
    const REDUCER_NAME: &'static str = "stdb_handle_place_block";
}

#[allow(unused)]
pub fn stdb_handle_place_block(player_id: u32, packet: StdbPlaceBlockPacket) {
    StdbHandlePlaceBlockArgs { player_id, packet }.invoke();
}

#[allow(unused)]
pub fn on_stdb_handle_place_block(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u32, &StdbPlaceBlockPacket)
        + Send
        + 'static,
) -> ReducerCallbackId<StdbHandlePlaceBlockArgs> {
    StdbHandlePlaceBlockArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let StdbHandlePlaceBlockArgs { player_id, packet } = __args;
        __callback(__identity, __addr, __status, player_id, packet);
    })
}

#[allow(unused)]
pub fn once_on_stdb_handle_place_block(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u32, &StdbPlaceBlockPacket)
        + Send
        + 'static,
) -> ReducerCallbackId<StdbHandlePlaceBlockArgs> {
    StdbHandlePlaceBlockArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let StdbHandlePlaceBlockArgs { player_id, packet } = __args;
        __callback(__identity, __addr, __status, player_id, packet);
    })
}

#[allow(unused)]
pub fn remove_on_stdb_handle_place_block(id: ReducerCallbackId<StdbHandlePlaceBlockArgs>) {
    StdbHandlePlaceBlockArgs::remove_on_reducer(id);
}
