// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::chunk_update_type::ChunkUpdateType;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbChunkUpdate {
    pub update_id: u32,
    pub chunk_id: u32,
    pub update_type: ChunkUpdateType,
}

impl TableType for StdbChunkUpdate {
    const TABLE_NAME: &'static str = "StdbChunkUpdate";
    type ReducerEvent = super::ReducerEvent;
}

impl StdbChunkUpdate {
    #[allow(unused)]
    pub fn filter_by_update_id(update_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.update_id == update_id)
    }
    #[allow(unused)]
    pub fn find_by_update_id(update_id: u32) -> Option<Self> {
        Self::find(|row| row.update_id == update_id)
    }
    #[allow(unused)]
    pub fn filter_by_chunk_id(chunk_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.chunk_id == chunk_id)
    }
}
