// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbInventory {
    pub inventory_id: u32,
    pub size: u32,
}

impl TableType for StdbInventory {
    const TABLE_NAME: &'static str = "StdbInventory";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for StdbInventory {
    type PrimaryKey = u32;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.inventory_id
    }
}

impl StdbInventory {
    #[allow(unused)]
    pub fn filter_by_inventory_id(inventory_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.inventory_id == inventory_id)
    }
    #[allow(unused)]
    pub fn find_by_inventory_id(inventory_id: u32) -> Option<Self> {
        Self::find(|row| row.inventory_id == inventory_id)
    }
    #[allow(unused)]
    pub fn filter_by_size(size: u32) -> TableIter<Self> {
        Self::filter(|row| row.size == size)
    }
}
