// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::item_stack::ItemStack;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbItemStack {
    pub stack_id: u32,
    pub inventory_id: u32,
    pub index: u32,
    pub stack: ItemStack,
}

impl TableType for StdbItemStack {
    const TABLE_NAME: &'static str = "StdbItemStack";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for StdbItemStack {
    type PrimaryKey = u32;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.stack_id
    }
}

impl StdbItemStack {
    #[allow(unused)]
    pub fn filter_by_stack_id(stack_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.stack_id == stack_id)
    }
    #[allow(unused)]
    pub fn find_by_stack_id(stack_id: u32) -> Option<Self> {
        Self::find(|row| row.stack_id == stack_id)
    }
    #[allow(unused)]
    pub fn filter_by_inventory_id(inventory_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.inventory_id == inventory_id)
    }
    #[allow(unused)]
    pub fn filter_by_index(index: u32) -> TableIter<Self> {
        Self::filter(|row| row.index == index)
    }
}
