// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbTime {
    pub id: i32,
    pub time: u64,
}

impl TableType for StdbTime {
    const TABLE_NAME: &'static str = "StdbTime";
    type ReducerEvent = super::ReducerEvent;
}

impl StdbTime {
    #[allow(unused)]
    pub fn filter_by_id(id: i32) -> TableIter<Self> {
        Self::filter(|row| row.id == id)
    }
    #[allow(unused)]
    pub fn find_by_id(id: i32) -> Option<Self> {
        Self::find(|row| row.id == id)
    }
    #[allow(unused)]
    pub fn filter_by_time(time: u64) -> TableIter<Self> {
        Self::filter(|row| row.time == time)
    }
}
