// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::stdb_i_32_vec_3::StdbI32Vec3;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbSetBlockEvent {
    pub pos: StdbI32Vec3,
    pub old_id: u8,
    pub old_metadata: u8,
    pub new_id: u8,
    pub new_metadata: u8,
}

impl TableType for StdbSetBlockEvent {
    const TABLE_NAME: &'static str = "StdbSetBlockEvent";
    type ReducerEvent = super::ReducerEvent;
}

impl StdbSetBlockEvent {
    #[allow(unused)]
    pub fn filter_by_old_id(old_id: u8) -> TableIter<Self> {
        Self::filter(|row| row.old_id == old_id)
    }
    #[allow(unused)]
    pub fn filter_by_old_metadata(old_metadata: u8) -> TableIter<Self> {
        Self::filter(|row| row.old_metadata == old_metadata)
    }
    #[allow(unused)]
    pub fn filter_by_new_id(new_id: u8) -> TableIter<Self> {
        Self::filter(|row| row.new_id == new_id)
    }
    #[allow(unused)]
    pub fn filter_by_new_metadata(new_metadata: u8) -> TableIter<Self> {
        Self::filter(|row| row.new_metadata == new_metadata)
    }
}
