// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::stdb_i_32_vec_3::StdbI32Vec3;
use super::stdb_window_kind::StdbWindowKind;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct StdbPlayerWindow {
    pub player_id: u32,
    pub kind: StdbWindowKind,
    pub pos: StdbI32Vec3,
}

impl TableType for StdbPlayerWindow {
    const TABLE_NAME: &'static str = "StdbPlayerWindow";
    type ReducerEvent = super::ReducerEvent;
}

impl StdbPlayerWindow {
    #[allow(unused)]
    pub fn filter_by_player_id(player_id: u32) -> TableIter<Self> {
        Self::filter(|row| row.player_id == player_id)
    }
}
