// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct TickArgs {}

impl Reducer for TickArgs {
    const REDUCER_NAME: &'static str = "tick";
}

#[allow(unused)]
pub fn tick() {
    TickArgs {}.invoke();
}

#[allow(unused)]
pub fn on_tick(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status) + Send + 'static,
) -> ReducerCallbackId<TickArgs> {
    TickArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let TickArgs {} = __args;
        __callback(__identity, __addr, __status);
    })
}

#[allow(unused)]
pub fn once_on_tick(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status) + Send + 'static,
) -> ReducerCallbackId<TickArgs> {
    TickArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let TickArgs {} = __args;
        __callback(__identity, __addr, __status);
    })
}

#[allow(unused)]
pub fn remove_on_tick(id: ReducerCallbackId<TickArgs>) {
    TickArgs::remove_on_reducer(id);
}
